name = "CSMP X"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33791c0e6af1be3010f2455cfdfb5ae511c2e3a0a17b003297e122da1f115eb2"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
