name = "CSMP X"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1b40e7b664586b7cfba0d6eb4cc05ca402075f854b752b64c8d11c3a972eefc"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
