name = "CSMP X"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8ed195bcea90b99c3c6f03e5a177c6a19811243ec9bffcd13567694bf101241"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
