name = "CSMP X"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60448d5a83d82e49343a3faefff250ed129454019c3fdfa46d3a040067f0dcc3"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
