name = "CSMP X"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f7f9919d42e636266d3efe60a9661548fd848a1cf0e002761780ff09ca9e6d7"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
