name = "CSMP X"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bbf80e21236fdd67485674aa088a15640dfad2d8dc33640c09edf9da20abb2a"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
